#配置项： 端口，mysql数据源，redis
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC

  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5 #最小空闲数
        max-idle: 10 #最大空闲数
        max-wait: -1 #-1：永不过期

  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB

# Show sql
logging:
  level:
    com:
      example:
        mapper: debug

# PageHelper
pagehelper:
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

